### ISSUE TITLE
clipboard requirement?

### ISSUE THREAD

**Issue by mcuix** [JesseAldridge/toothbrush#1]
Where do I get the "clipboard" requirement?

**Comment by mcuix** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/t", line 4, in <module>
    import clipboard
ImportError: No module named clipboard
```

**Comment by JesseAldridge** [comment]
Hey sorry, didn't notice your issue.  I removed the requirement.  It wasn't very useful anyway.
I'll add instructions to the readme if I add any third party libs in the future.
